### ISSUE TITLE
Error in hero component when initially loading page.

### ISSUE THREAD

**Issue by Aebel-Shajan** [Aebel-Shajan/nemo-movies#9]
Error :
```
Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at Hero (http://localhost:3000/static/js/bundle.js:290:24)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:101908:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:105879:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:107182:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:92164:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:92208:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:92265:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:112163:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:111411:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:111334:9)
```

**Comment by Aebel-Shajan** [comment]
This error was caused becuase the initial state of the movie state was not set to anything. This meant the method movies.map() could not execute in Hero.js.
